services:
  - type: web
    name: yii2-app
    env: php
    plan: free
    buildCommand: "composer install --no-interaction --prefer-dist --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:$PORT -t web/"
    envVars:
      - key: APP_ENV
        value: production
    autoDeploy: true
    runtime: php
